sudo: required
language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install wkhtmltopdf
  - sudo apt-get install Xvfb
install:
  - pip install setuptools --upgrade
  - pip install nose
  - python setup.py install
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=codeforcesDl
after_success:
  coveralls
notifications:
  email: false
